#!/bin/bash

echo "🚀 IIIT Kalyani Chatbot - Deployment Guide"
echo "=========================================="
echo ""

echo "📦 Step 1: Push to GitHub"
echo "-------------------------"
echo "Run these commands:"
echo ""
echo "  git add ."
echo "  git commit -m \"Initial commit - College Chatbot\""
echo "  git branch -M main"
echo "  git remote add origin https://github.com/Anurag02012004/College-ChatBot.git"
echo "  git push -u origin main"
echo ""

echo "🖥️  Step 2: Deploy Backend to Render"
echo "------------------------------------"
echo "1. Go to https://render.com and sign in with GitHub"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository: Anurag02012004/College-ChatBot"
echo "4. Render will auto-detect settings from render.yaml"
echo "5. Click 'Create Web Service'"
echo "6. Wait for deployment (5-10 minutes for first time)"
echo "7. Copy your backend URL (e.g., https://college-chatbot.onrender.com)"
echo ""

echo "🌐 Step 3: Deploy Frontend to Netlify"
echo "-------------------------------------"
echo "1. Go to https://netlify.com and sign in with GitHub"
echo "2. Click 'Add new site' → 'Import an existing project'"
echo "3. Choose GitHub and select your repository"
echo "4. Configure:"
echo "   - Base directory: static-frontend"
echo "   - Build command: (leave empty)"
echo "   - Publish directory: ."
echo "5. Before deploying, update index.html with your backend URL:"
echo "   - Edit static-frontend/index.html"
echo "   - Change: const API_URL = 'https://YOUR-BACKEND-URL.onrender.com';"
echo "6. Click 'Deploy site'"
echo ""

echo "✅ Step 4: Test Your Deployment"
echo "-------------------------------"
echo "1. Visit your Netlify URL"
echo "2. Try asking: 'Tell me about Dr. Anirban Lakshman'"
echo "3. Check if responses are formatted correctly"
echo ""

echo "📝 Additional Notes:"
echo "- Backend (Render free tier): First request may take 30s (cold start)"
echo "- Frontend (Netlify): Unlimited bandwidth, instant load"
echo "- Update netlify.toml with your actual backend URL"
echo ""

echo "Need help? Check DEPLOYMENT.md for detailed instructions!"
